### ISSUE TITLE
pdf file is not created 

### ISSUE THREAD

**Issue by maiananthan** [captn3m0/ickabog-ebook#3]
pdf file is not created when using directly method

Below is the command came out
_mv: cannot stat 'out/ickabog-no-cover.pdf': No such file or directory_

**Comment by captn3m0** [comment]
Can you try running this (against latest master) please? I'm guessing you didn't have `xelatex` installed, so added an error message for that.

**Comment by maiananthan** [comment]
> Can you try running this (against latest master) please? I'm guessing you didn't have `xelatex` installed, so added an error message for that.

Got it. Thanks :)
